# Welcome!

badges

Guidebook is about...

## Who you are as the reader

We've written these documents considering a few people in mind who we
think will read the documents:

-   **New contributors/team members**: ...
-   **Research software/data engineers**: ...
-   **Managers or leaders**: ...
-   **Research or development operations personnel**: ...

These documents contained within the style section are meant to provide
guidance on how to write, format, and structure documents within the
Seedcase Project. They are meant to be a guide and a reference for all
team members and contributors to make sure that we have some consistency
in development, coding, and writing across all Seedcase documentation
and software.

We assume the reader is either:

-   A new team member who uses these style documents as onboarding
    material.
-   A current team member who needs to reference the style documents for
    a specific task or as a reminder.
-   A potential or current contributor who wants to understand how we
    work and how to best contribute.
-   Other groups who want to use these documents as inspiration or to
    copy/modify for their own uses.

Following our Seedcase Project
[principles](https://seedcase-project.org/about/principles) to use
established standards and conventions, the general principle for styling
is to use existing guides. There exist several style guides and
resources for structuring code and doing software development, below are
specific guides we make use of:

(link to design)



## Who you are as the reader

We've written these documents considering a few people in mind who we
think will read the documents:

-   **New contributors/team members**: The most important reason we have
    written design documentation is to quickly onboard new contributors
    or team members to the project.

-   **Research software/data engineers**: These readers will be
    interested in how we design our software and potentially our
    organisation, likely for their own purposes for learning or for
    using in their own work.

-   **Managers or leaders**: These are people that maybe be interested
    in applying what we do to their own organisation, team, or group.

-   **Research or development operations personnel**: This reader is a
    person who is interested in applying or learning from how we manage
    our operations and how streamline or automate our operational tasks.
